### ISSUE TITLE
Enchantment: Send ping as embed

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-discord-ping-formatter#13]
Pings look very messy in the channel since they are not sent out in blocks. Specially when you do not belong to the group that is pinged it is very hard to determine where an old ping stops and where a new ping starts.

To fix this and make the ping list on discord look a lot cleaner you could include the ping content into an embed block. This way each ping is grouped up nicely.

**Comment by ppfeufer** [comment]
That's actually on my list, so, soon(tm) ....

**Comment by ppfeufer** [comment]
I played a bit around with embeds and they are too small and harder to read compared to a proper text ping.

![2ccd81ad0420](https://user-images.githubusercontent.com/2989985/87625774-41390b00-c72b-11ea-8000-2906c9eb4032.jpg)

So I leave it as it is for now.

**Comment by ppfeufer** [comment]
LOL, I think I started a war in corp and alliance by asking which version they find better ...

Let's see how that turns out, you might get your embeds (with some other stuff as well)

**Comment by paulipa** [comment]
personally i still like the embed one. Could always leave an settings option to toggle it on? ;)

**Comment by ppfeufer** [comment]
For the embedded version are quite some changes in JavaScript needed. So simply an option doesn't cut it.

**Comment by paulipa** [comment]
Well then take my vote for the embed version. I do not think its too small and i like all information in nice blocks for easier navigation. Hope your corp agrees:P

**Comment by ppfeufer** [comment]
There is a valid argument for the normal version some raise 

> if i see the black box, i have tendency to ignore
black box remind me of links or battle reports

**Comment by ppfeufer** [comment]
Implemented as option, Have fun.
