### ISSUE TITLE
[Feature Suggestion] Dynamic Dropdown Menu/Textbox

### ISSUE THREAD

**Issue by exiom-xyz** [ppfeufer/aa-discord-ping-formatter#24]
Idea:
Fleet Comms: [Dropdown Menu]
when the user selects a preconfigured item
field turns into a textbox for further editing

Same idea can also work nicely for Formup and Doctrine as well...

**Comment by ppfeufer** [comment]
I guess you mean something ike this?

https://www.javatpoint.com/oprweb/test.jsp?filename=htmldatalisttag1
