### ISSUE TITLE
Cant ping additional ping targets via direct ping

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-discord-ping-formatter#9]
When trying to ping additional ping targets via the webhook the roles do not get pinged. Ping for everyone and for here works but other pings such as @ceo or @special interests: mining does not ping anything. Copy paste format works and pings the roles but id like to use this with the webhook option forced on.

**Comment by ppfeufer** [comment]
Yep, you are right. Webhooks ping a bit different/need a different syntax ... have to change the config a bit for that. Give me a bit to fix it.

**Comment by ppfeufer** [comment]
**Settings changed** - The format of `AA_DISCORDFORMATTER_ADDITIONAL_PING_TARGETS` has been changed in order to fix the ping via webhook. Please make sure to adjust it accordingly.
